version: '3'
services:
  frontend:
    # image: ${IMAGE_NAME}:${IMAGE_TAG}
    image: crystal505/videosharing_react_test:1407a083
    ports:
      - 443:443
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt
