name: Build & Deploy development with options

on:
  workflow_dispatch:
    inputs:
      serverSelection:
        description: "Enter server number (e.g., 1 for SERVER 1, 2 for SERVER 2)"
        required: true


jobs:

  docker_build_Development:
    runs-on: ubuntu-latest
    environment:
      name: development
    outputs:
      IMAGE_TAG: ${{ steps.build_image.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        id: build_image
        env:
          DOMAIN_KEY_NAME: ${{ format('DOMAIN_NAME_{0}', inputs.serverSelection) }}
          DOMAIN_NAME: ${{ env[env.DOMAIN_KEY_NAME] }}
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
            echo "Building image with tag ${IMAGE_TAG}"
            envsubst '$DOMAIN_NAME' < domain.conf.template > default.conf
            envsubst '$DOMAIN_NAME' < Dockerfile.template > Dockerfile.server
            docker build . -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
            echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}"
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}

  Deployment:
    needs: [docker_build_Development]
    uses: ./.github/workflows/_deploy-template.yml
    secrets: inherit
    with:
      DOCKER_IMAGE_TAG: ${{ needs.docker_build_Development.outputs.IMAGE_TAG }}
      serverSelection: ${{ github.event.inputs.serverSelection }}
      environmentName: development
      approvalEnvironmentName: approval_development_deloyment
