name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  docker_build:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: test
      # url: ${{ steps.deploy.outputs.url }}
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        echo "Building image with tag ${IMAGE_TAG}"
        docker build . -f Dockerfile.staging -t ${{ secrets.DOCKER_USERNAME }}/videosharing_react_staging:${IMAGE_TAG}
        echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/videosharing_react_staging:${IMAGE_TAG}"
        docker push ${{ secrets.DOCKER_USERNAME }}/videosharing_react_staging:${IMAGE_TAG}
