name: CI/CD

on:
  pull_request:
    branches:
    - develop
    - main

  push:
    branches:
      - develop
    tags:
      - "v*.*.*"


jobs:
  run:
    uses: ./.github/workflows/_ci_cd_template.yml
    secrets: inherit
