name: CI Development

on:
  pull_request:
    branches:
    - develop

    types: [opened, synchronize, reopened]


jobs:
  run_test_Development:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  need_merge_develop_approval:
    runs-on: ubuntu-latest
    environment:
      name: approval_merge_develop_branch
    steps:
      - name: Wait for merge approval 
        run: echo "Waiting for admin merge approval..."
