name: Deploy to Development Server

on:
  # Allows run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        DOCKER_IMAGE_TAG:
            description: "Docker image tag"
            required: true

        serverSelection:
            description: "Enter server number (e.g., 1 for SERVER 1, 2 for SERVER 2)"
            required: true

jobs:
    development_server_deployment:
        uses: ./.github/workflows/_deploy-template.yml
        secrets: inherit
        with:
            DOCKER_IMAGE_TAG: ${{ github.event.inputs.DOCKER_IMAGE_TAG }}
            serverSelection: ${{ github.event.inputs.serverSelection }}
            environmentName: development
            approvalEnvironmentName: approval_development_environment
