name: Deploy Development

on:
  issue_comment:
    types: 
      - created

jobs:
  check-pr-status:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build_and_deploy_s')
    runs-on: ubuntu-latest
    outputs:
      is_open: ${{ steps.pr_status.outputs.is_open }}
    steps:
      - name: Check if PR is open
        id: pr_status
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.data.state;

  docker_build_Development:
    needs: check-pr-status
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/build_and_deploy_s') && needs.check-pr-status.outputs.is_open == 'open'
    runs-on: ubuntu-latest
    environment:
      name: development
    outputs:
      IMAGE_TAG: ${{ steps.build_image.outputs.IMAGE_TAG }}
    steps:
    - uses: actions/checkout@v2

    - name: Extract server number
      id: server
      run: echo "SERVER_NUMBER=$(echo ${{ github.event.comment.body }} | grep -o -E 's[0-9]+' | cut -c2-)" >> $GITHUB_ENV
 



      

    - name: Create env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      id: build_image
      env:
        DOMAIN_KEY_NAME: ${{ format('DOMAIN_NAME_{0}', env.SERVER_NUMBER) }}
        DOMAIN_NAME: ${{ vars[env.DOMAIN_KEY_NAME] }}
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT
        echo "Building image with tag ${IMAGE_TAG}"
        envsubst '$DOMAIN_NAME' < domain.conf.template > default.conf
        envsubst '$DOMAIN_NAME' < Dockerfile.template > Dockerfile.server
        docker build . -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
        echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}"
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
